<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yiqing Hu, Rahila Mammadova Huseynova">

<title>Analysis of User Preferences between AI-generated and Hand-drawn Artwork: A Case Study of pixiv.net</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="ordered_model_files/libs/clipboard/clipboard.min.js"></script>
<script src="ordered_model_files/libs/quarto-html/quarto.js"></script>
<script src="ordered_model_files/libs/quarto-html/popper.min.js"></script>
<script src="ordered_model_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ordered_model_files/libs/quarto-html/anchor.min.js"></script>
<link href="ordered_model_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ordered_model_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="ordered_model_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="ordered_model_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ordered_model_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ordered_model_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="ordered_model_files/libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Analysis of User Preferences between AI-generated and Hand-drawn Artwork: A Case Study of pixiv.net</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Yiqing Hu, Rahila Mammadova Huseynova </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">5/30/23</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#samples" id="toc-samples" class="nav-link" data-scroll-target="#samples"><span class="header-section-number">2.1</span> Samples</a></li>
  <li><a href="#parameters" id="toc-parameters" class="nav-link" data-scroll-target="#parameters"><span class="header-section-number">2.2</span> Parameters</a></li>
  </ul></li>
  <li><a href="#model-varification" id="toc-model-varification" class="nav-link" data-scroll-target="#model-varification"><span class="header-section-number">3</span> Model Varification</a>
  <ul class="collapse">
  <li><a href="#covariates-and-model-selection" id="toc-covariates-and-model-selection" class="nav-link" data-scroll-target="#covariates-and-model-selection"><span class="header-section-number">3.1</span> Covariates and Model Selection</a></li>
  <li><a href="#goodness-of-fit-tests" id="toc-goodness-of-fit-tests" class="nav-link" data-scroll-target="#goodness-of-fit-tests"><span class="header-section-number">3.2</span> Goodness-of-fit tests</a></li>
  <li><a href="#odds-assumption-test" id="toc-odds-assumption-test" class="nav-link" data-scroll-target="#odds-assumption-test"><span class="header-section-number">3.3</span> Odds Assumption Test</a></li>
  <li><a href="#r2-statistics" id="toc-r2-statistics" class="nav-link" data-scroll-target="#r2-statistics"><span class="header-section-number">3.4</span> R2 statistics</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection"><span class="header-section-number">3.5</span> Model Selection</a></li>
  </ul></li>
  <li><a href="#model-estimating" id="toc-model-estimating" class="nav-link" data-scroll-target="#model-estimating"><span class="header-section-number">4</span> Model Estimating</a>
  <ul class="collapse">
  <li><a href="#general" id="toc-general" class="nav-link" data-scroll-target="#general"><span class="header-section-number">4.1</span> General</a></li>
  <li><a href="#marginal-effects" id="toc-marginal-effects" class="nav-link" data-scroll-target="#marginal-effects"><span class="header-section-number">4.2</span> Marginal Effects</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">5</span> Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<hr>
<p>The emergence of AI drawing models, such as Stable-Diffusion (SD) and Midjourney, has led to a significant influx of AI-generated images in the online art community. In this study, we collected daily rankings of the top 50 AI-generated images and hand-drawn artwork from <a href="http://pixiv.net">pixiv.net</a>. Our objective was to explore the factors/variables influencing the ranking of these images and examine the preferences of ordinary users towards AI-generated images versus hand-drawn artwork. The findings from this study will contribute to a better understanding of the impact of AI-generated artwork on user preferences and provide insights for the development of AI-assisted creative platforms.</p>
<p>References Test<br> dasfasdfas<span class="citation" data-cites="EconomicsChatGPT"><a href="#ref-EconomicsChatGPT" role="doc-biblioref">[1]</a></span><br> dasdasdsa<span class="citation" data-cites="AIThemedCryptocurrencies"><a href="#ref-AIThemedCryptocurrencies" role="doc-biblioref">[2]</a></span></p>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<hr>
<p>This study utilizes data collected from <a href="http://pixiv.net">pixiv.net</a>, a popular platform for painters to share their artwork, to investigate the impact of AI-generated artworks on user-generated content. Starting from November of the previous year, the platform has witnessed a continuous influx of AI-generated works. The dataset comprises information such as tags, Views, Likes, Bookmarks, and Comments for the Top 50 artworks or pictures each day, spanning from October 31, 2022, to May 15, 2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pixiv <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../data/pixiv_tops_lm.csv'</span>,<span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">","</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">as.integer</span>((pixiv<span class="sc">$</span>rank<span class="dv">-1</span>) <span class="sc">/</span> <span class="dv">10</span>)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>is_comic <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(pixiv<span class="sc">$</span>is_comic)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>is_Genshin <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(pixiv<span class="sc">$</span>is_Genshin)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>is_Honkai <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(pixiv<span class="sc">$</span>is_Honkai)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>views <span class="ot">&lt;-</span>pixiv<span class="sc">$</span>views<span class="sc">/</span><span class="dv">1000</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>like_rate2 <span class="ot">&lt;-</span> pixiv<span class="sc">$</span>like_rate<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>pixiv<span class="sc">$</span>mark_rate2 <span class="ot">&lt;-</span> pixiv<span class="sc">$</span>mark_rate<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># pixiv$views &lt;- scale(pixiv$views)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="samples" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="samples"><span class="header-section-number">2.1</span> Samples</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ai <span class="ot">&lt;-</span> pixiv[pixiv<span class="sc">$</span>is_ai <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>man <span class="ot">&lt;-</span> pixiv[pixiv<span class="sc">$</span>is_ai <span class="sc">==</span> <span class="dv">0</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Number of all samples: 14576 <br> Number of samples of AI-generated artworks: 8092 <br> Number of samples of Hand-drawn Artworks: 6484 <br></p>
</section>
<section id="parameters" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="parameters"><span class="header-section-number">2.2</span> Parameters</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pid</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">artworkpage id</td>
</tr>
<tr class="even">
<td style="text-align: left;">date</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">date of being top50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">like_rate</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">ratio of liked amount of viewed amount</td>
</tr>
<tr class="even">
<td style="text-align: left;">mark_rate</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">ratio of bookmarked number of viewed number</td>
</tr>
<tr class="odd">
<td style="text-align: left;">is_comic</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">whether the artwork is comic</td>
</tr>
<tr class="even">
<td style="text-align: left;">is_ai</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">whether the artwork is generated by AI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">is_Genshin</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">whether the artwork is about Genshin</td>
</tr>
<tr class="even">
<td style="text-align: left;">is_Honkai</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">whether the artwork is about Honkai</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comments</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">comment amount</td>
</tr>
<tr class="even">
<td style="text-align: left;">views</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">viewed amount in thousand</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rank</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">dependent variable</td>
</tr>
<tr class="even">
<td style="text-align: left;">top_cnt</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">how many times being top50 for the same artwork</td>
</tr>
<tr class="odd">
<td style="text-align: left;">date_diff_day</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">date difference between created and being top</td>
</tr>
<tr class="even">
<td style="text-align: left;">like_rate2</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">power of like_rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mark_rate2</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">power of mark_rate</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="model-varification" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Model Varification</h1>
<hr>
<section id="covariates-and-model-selection" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="covariates-and-model-selection"><span class="header-section-number">3.1</span> Covariates and Model Selection</h2>
<p>our research focuses on analyzing the influence of different independent variables on the rankings in the daily top 50 list on pixiv.net. Our objective is to develop an evaluation model that effectively captures the factors affecting the rankings.</p>
<p>The granularity of the rankings, ranging from 1 to 50, is excessively detailed for our analysis. To address this issue, we have categorized the rankings into five levels by dividing the range equally. The formula is below: <span class="math display">\[
\text{tier} = \left\lfloor \frac{{\text{{rank}} - 1}}{{10}} \right\rfloor + 1
\]</span></p>
<p>This categorized rank will serve as our dependent variable, enabling us to better understand the impact of the independent variables on the rankings.</p>
<p>Given that the categorized rank is an ordered, continuous, and discrete variable with five levels, employing an ordered choice model is a suitable approach. Therefore, we will utilize both the ordered logit and ordered probit models for our subsequent analysis, allowing us to effectively examine the relationships between the independent variables and the categorized rankings.</p>
<p>The logit model in R for our task is below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>tier<span class="ot">&lt;-</span><span class="fu">as.factor</span>(ai<span class="sc">$</span>rank)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>logit_ai <span class="ot">&lt;-</span> <span class="fu">polr</span>(tier<span class="sc">~</span>like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin<span class="sc">+</span>is_Honkai</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>views</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                 ,<span class="at">data=</span>ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="goodness-of-fit-tests" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="goodness-of-fit-tests"><span class="header-section-number">3.2</span> Goodness-of-fit tests</h2>
<section id="hosmer-lemeshow-and-lipsitz-tests" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="hosmer-lemeshow-and-lipsitz-tests"><span class="header-section-number">3.2.1</span> Hosmer-Lemeshow and Lipsitz tests</h3>
<p>the H0 of Lipsitz and logitgof is the form of our model is appropriate. If one of them is un-appropriate. we say the model has a problem, we need to correct the model. Only if both test get the model is appropriate, then we can say the model is appropriate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lipsitz.test</span>(logit_ai) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lipsitz goodness of fit test for ordinal response models

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day + views
LR statistic = 38.335, df = 9, p-value = 0.00001517</code></pre>
</div>
</div>
<p>p-value is 0.0000002942 &lt; 5%, can’t reject the H0, so the form of our model has a problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logitgof</span>(tier, <span class="fu">fitted</span>(logit_ai), <span class="at">g=</span><span class="dv">5</span>, <span class="at">ord =</span> <span class="cn">TRUE</span>) <span class="co"># Lemeshow</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow test (ordinal model)

data:  tier, fitted(logit_ai)
X-squared = 35.749, df = 15, p-value = 0.001921</code></pre>
</div>
</div>
<p>p-value is 0.00007257 &lt; 5%, can’t reject the H0, so the form of our model has a problem.</p>
</section>
<section id="pulkstenis-robinson-tests" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="pulkstenis-robinson-tests"><span class="header-section-number">3.2.2</span> Pulkstenis-Robinson tests</h3>
<p>Only if we have dummy variable, we can use robinson test. Our model has three dummy variables which are “is_comic”,‘is_Genshin’ and ‘is_Honkai’, so it is better to use Robinson test instead of Hosmer-Lemeshow and Lipsitz.</p>
<p>Because our prof and the doc do not mention the null hypothesises of these two methods, so I asked ChatGPT:</p>
<p>pulkrob.chisq: The null hypothesis is that there is no significant departure from the expected frequencies in the observed data based on the ordinal logistic regression model. In other words, the model fits the observed data well, and there is no evidence of lack of fit.</p>
<p>pulkrob.deviance: The null hypothesis is that the simpler model, which is usually the null or baseline model, provides an equally good fit to the data as the more complex model. In other words, the additional predictors in the more complex model do not significantly improve the model fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pulkrob.chisq</span>(logit_ai, <span class="fu">c</span>(<span class="st">"is_comic"</span>,<span class="st">'is_Genshin'</span>, <span class="st">'is_Honkai'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pulkstenis-Robinson chi-squared test

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day + views
X-squared = 62.54, df = 44, p-value = 0.03432</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pulkrob.deviance</span>(logit_ai, <span class="fu">c</span>(<span class="st">"is_comic"</span>,<span class="st">'is_Genshin'</span>, <span class="st">'is_Honkai'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pulkstenis-Robinson deviance test

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day + views
Deviance-squared = 66.315, df = 44, p-value = 0.01643</code></pre>
</div>
</div>
<p>Base on the null hypothesis ChatGPT gives us: we reject the H0 of Pulkstenis-Robinson chi-squared test with p-value equals to 0.03315 &lt; 5%, means the model doesn’t fit the observed data well. We reject the H0 of Pulkstenis-Robinson deviance test with p-value equals to 0.01776 &lt; 5%, means the additional predictors in the more complex model significantly improve the model fit.</p>
<p>From the results of Goodness-of-fit tests, we notice that the the model for our task is not appropriate. So we remove the parameter of ‘views’ to check Goodness-of-fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>logit_ai <span class="ot">&lt;-</span> <span class="fu">polr</span>(tier<span class="sc">~</span>like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin<span class="sc">+</span>is_Honkai</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                  , <span class="at">data=</span>ai)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pulkrob.chisq</span>(logit_ai, <span class="fu">c</span>(<span class="st">"is_comic"</span>,<span class="st">'is_Genshin'</span>, <span class="st">'is_Honkai'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pulkstenis-Robinson chi-squared test

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day
X-squared = 49.559, df = 44, p-value = 0.2612</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pulkrob.deviance</span>(logit_ai, <span class="fu">c</span>(<span class="st">"is_comic"</span>,<span class="st">'is_Genshin'</span>, <span class="st">'is_Honkai'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pulkstenis-Robinson deviance test

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day
Deviance-squared = 51.026, df = 44, p-value = 0.2169</code></pre>
</div>
</div>
<p>Now the p-value of chi-squared and deviance tests of Pulkstenis-Robinso are all larger than 5%, so we can not reject the H0 any more, so we can get the conclusion that the model without ‘views’ is appropriate.</p>
</section>
</section>
<section id="odds-assumption-test" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="odds-assumption-test"><span class="header-section-number">3.3</span> Odds Assumption Test</h2>
<section id="brants-test" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="brants-test"><span class="header-section-number">3.3.1</span> Brant’s test</h3>
<p>This test is to verify the proportional add assumption, the function works with polr model results. This test concludes which variable is connected to the rejection of a test. Brant’s test’s H0 is Parallel Regression Assumption holds.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">brant</span>(logit_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-------------------------------------------- 
Test for    X2  df  probability 
-------------------------------------------- 
Omnibus     67.41   24  0
like_rate   24.02   3   0
mark_rate   23.95   3   0
is_comic1   0.73    3   0.87
is_Genshin1 3.56    3   0.31
is_Honkai1  1.72    3   0.63
comments    15.3    3   0
top_cnt     27.15   3   0
date_diff_day   8.96    3   0.03
-------------------------------------------- 

H0: Parallel Regression Assumption holds</code></pre>
</div>
</div>
<p>we should focus on the first line - Omnibus, it contains test statistic for the test and the p-value. Test statistic(X2) is 67.41 and probability(p-value) is 0, so we have to reject the null hypothesis, so Parallel Regression Assumption doesn’t hold, so our model is not fine. so we shouldn’t use ordered logit model. The variables with the probability higher than 5% indicate if it is connected to the rejection of a test. So instead of using ordered logit model, we should choose ordered profit model which does not have the proportional odds assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ai<span class="sc">$</span>tier<span class="ot">&lt;-</span><span class="fu">as.factor</span>(ai<span class="sc">$</span>rank)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>probit_ai <span class="ot">&lt;-</span> <span class="fu">clm</span>(tier<span class="sc">~</span>like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin<span class="sc">+</span>is_Honkai</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                  , <span class="at">data=</span>ai, <span class="at">link=</span><span class="fu">c</span>(<span class="st">'probit'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="r2-statistics" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="r2-statistics"><span class="header-section-number">3.4</span> R2 statistics</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(logit_ai) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            llh         llhNull              G2        McFadden            r2ML 
-11958.42802746 -13021.45804846   2126.06004201      0.08163679      0.23105516 
           r2CU 
     0.24068770 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(probit_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            llh         llhNull              G2        McFadden            r2ML 
-11949.44891673 -13021.45804846   2144.01826346      0.08232635      0.23275975 
           r2CU 
     0.24246335 </code></pre>
</div>
</div>
<p>R2 for logit model cannot be explained alone, for example, the value of McFadden must be compared with other models to be interpreted. McFadden R2 of probit model is 0.0823 comparing the McFadden R2 of logit which is0.0872, the McFadden R2 of probit is lower than logit, which means probit model is more suitable in this situation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pulkrob.chisq</span>(probit_ai, <span class="fu">c</span>(<span class="st">"is_comic"</span>,<span class="st">'is_Genshin'</span>, <span class="st">'is_Honkai'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pulkstenis-Robinson chi-squared test

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day
X-squared = 46.082, df = 44, p-value = 0.3861</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pulkrob.deviance</span>(probit_ai, <span class="fu">c</span>(<span class="st">"is_comic"</span>,<span class="st">'is_Genshin'</span>, <span class="st">'is_Honkai'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pulkstenis-Robinson deviance test

data:  formula:  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + formula:      comments + top_cnt + date_diff_day
Deviance-squared = 47.417, df = 44, p-value = 0.3351</code></pre>
</div>
</div>
<p>Of course, the goodness-of-fit tests of Pulkstenis-Robinson also give the prove that the probit model is suitable.</p>
</section>
<section id="model-selection" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="model-selection"><span class="header-section-number">3.5</span> Model Selection</h2>
<section id="likelihood-ratio-test" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="likelihood-ratio-test"><span class="header-section-number">3.5.1</span> Likelihood Ratio Test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>probit_ai_restricted <span class="ot">&lt;-</span> <span class="fu">clm</span>(<span class="fu">as.factor</span>(tier)<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>ai)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(probit_ai, probit_ai_restricted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + 
    comments + top_cnt + date_diff_day
Model 2: as.factor(tier) ~ 1
  #Df LogLik Df Chisq            Pr(&gt;Chisq)    
1  12 -11949                                   
2   4 -13022 -8  2144 &lt; 0.00000000000000022 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The restricted model with constant only:as.factor(tier)~1, the p-value of the likelihood ratio test statistic associated with test statistics is almost 0 &lt; 5%, we have to reject the H0: beta1=beta2=0 (which is the condition of restriction), so they jointly significant. so we should choose unrestricted model.</p>
</section>
<section id="test-for-variables-to-their-powers" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="test-for-variables-to-their-powers"><span class="header-section-number">3.5.2</span> Test for variables to their powers</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>probit_ai_power <span class="ot">&lt;-</span> <span class="fu">clm</span>(tier <span class="sc">~</span> like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin<span class="sc">+</span>is_Honkai</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>like_rate2<span class="sc">+</span>mark_rate2, <span class="at">data =</span> ai, <span class="at">link=</span><span class="fu">c</span>(<span class="st">'probit'</span>))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(probit_ai, probit_ai_power)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
                formula:                                                                                                                       
probit_ai       tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + comments + top_cnt + date_diff_day                          
probit_ai_power tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + comments + top_cnt + date_diff_day + like_rate2 + mark_rate2
                link:  threshold:
probit_ai       probit flexible  
probit_ai_power probit flexible  

                no.par   AIC logLik LR.stat df Pr(&gt;Chisq)    
probit_ai           12 23923 -11949                          
probit_ai_power     14 23909 -11940  18.048  2  0.0001205 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>p-value equals to 0.00012 &lt; 5%, we have to reject the null hypothesis which is the power of beta of like_rate is 0 and beta power of mark_rate is 0,in other words, two models are equal, so these two models are significantly different, so the model probit_ai without ‘is_Honkai1’ and powers of like_rate and mark_rate would be better than the one without powers.</p>
</section>
<section id="variables-selection" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="variables-selection"><span class="header-section-number">3.5.3</span> Variables Selection</h3>
<p>general-to-specific method to variables selection for AI model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(probit_ai_power)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                 Estimate  Std. Error  t value              Pr(&gt;|t|)    
1|2            -1.3606197   0.1131953 -12.0201 &lt; 0.00000000000000022 ***
2|3            -0.6567886   0.1126169  -5.8321        0.000000005686 ***
3|4            -0.0728850   0.1124906  -0.6479             0.5170546    
4|5             0.5668039   0.1126528   5.0314        0.000000497345 ***
like_rate     -12.2456027   3.7323739  -3.2809             0.0010391 ** 
mark_rate      10.3938217   2.1123227   4.9206        0.000000880009 ***
is_comic1       0.8637065   0.2396678   3.6038             0.0003155 ***
is_Genshin1    -0.1283309   0.0265285  -4.8375        0.000001339375 ***
is_Honkai1     -0.0568993   0.0486479  -1.1696             0.2421902    
comments       -0.0327167   0.0030684 -10.6623 &lt; 0.00000000000000022 ***
top_cnt        -0.5618988   0.0197977 -28.3820 &lt; 0.00000000000000022 ***
date_diff_day  -0.2652163   0.0266711  -9.9440 &lt; 0.00000000000000022 ***
like_rate2      5.4639612  12.4129091   0.4402             0.6598158    
mark_rate2    -10.0575579   4.0767402  -2.4671             0.0136434 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We find the p-value of ‘like_rate2’ and ‘is_Honkai1’ are lower than 5%, these two parameters are insignificant for the model, so we will deal with the the process of general-to-specific method for them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>probit_ai_honkai <span class="ot">&lt;-</span> <span class="fu">clm</span>(tier <span class="sc">~</span> like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>like_rate2<span class="sc">+</span>mark_rate2</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                  , <span class="at">data =</span> ai, <span class="at">link=</span><span class="fu">c</span>(<span class="st">'probit'</span>))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(probit_ai_power, probit_ai_honkai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
                 formula:                                                                                                                       
probit_ai_honkai tier ~ like_rate + mark_rate + is_comic + is_Genshin + comments + top_cnt + date_diff_day + like_rate2 + mark_rate2            
probit_ai_power  tier ~ like_rate + mark_rate + is_comic + is_Genshin + is_Honkai + comments + top_cnt + date_diff_day + like_rate2 + mark_rate2
                 link:  threshold:
probit_ai_honkai probit flexible  
probit_ai_power  probit flexible  

                 no.par   AIC logLik LR.stat df Pr(&gt;Chisq)
probit_ai_honkai     13 23908 -11941                      
probit_ai_power      14 23909 -11940  1.3683  1     0.2421</code></pre>
</div>
</div>
<p>p-value=0.24&gt;0.05, we can’t reject the null hypothesis, so two model is the same, then we can choose a better on with less parameters which is the one without variable is_Honkai.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>probit_ai_honkai_liked2 <span class="ot">&lt;-</span> <span class="fu">clm</span>(tier <span class="sc">~</span> like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>mark_rate2, <span class="at">data =</span> ai, <span class="at">link=</span><span class="fu">c</span>(<span class="st">'probit'</span>))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(probit_ai_honkai, probit_ai_honkai_liked2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
                        formula:                                                                                                           
probit_ai_honkai_liked2 tier ~ like_rate + mark_rate + is_comic + is_Genshin + comments + top_cnt + date_diff_day + mark_rate2             
probit_ai_honkai        tier ~ like_rate + mark_rate + is_comic + is_Genshin + comments + top_cnt + date_diff_day + like_rate2 + mark_rate2
                        link:  threshold:
probit_ai_honkai_liked2 probit flexible  
probit_ai_honkai        probit flexible  

                        no.par   AIC logLik LR.stat df Pr(&gt;Chisq)
probit_ai_honkai_liked2     12 23906 -11941                      
probit_ai_honkai            13 23908 -11941  0.2185  1     0.6402</code></pre>
</div>
</div>
<p>p-value=0.24&gt;0.05, we can’t reject the null hypothesis, so two model is the same, then we can choose a better on with less parameters which is the one without variable ‘like_rate2’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(probit_ai_honkai_liked2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                 Estimate  Std. Error  t value              Pr(&gt;|t|)    
1|2            -1.3509496   0.1061138 -12.7311 &lt; 0.00000000000000022 ***
2|3            -0.6472379   0.1055069  -6.1346       0.0000000008942 ***
3|4            -0.0634168   0.1053794  -0.6018             0.5473275    
4|5             0.5762096   0.1055595   5.4586       0.0000000494062 ***
like_rate     -10.8387234   0.8874689 -12.2131 &lt; 0.00000000000000022 ***
mark_rate       9.6129323   1.1346571   8.4721 &lt; 0.00000000000000022 ***
is_comic1       0.8625165   0.2396125   3.5996             0.0003206 ***
is_Genshin1    -0.1201951   0.0256356  -4.6886       0.0000027958857 ***
comments       -0.0326257   0.0030563 -10.6750 &lt; 0.00000000000000022 ***
top_cnt        -0.5623914   0.0197902 -28.4177 &lt; 0.00000000000000022 ***
date_diff_day  -0.2648563   0.0266642  -9.9330 &lt; 0.00000000000000022 ***
mark_rate2     -8.3242784   2.0056964  -4.1503       0.0000335421048 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>After checking the result of coeftest, all parameters are significant now.</p>
</section>
</section>
</section>
<section id="model-estimating" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Model Estimating</h1>
<section id="general" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="general"><span class="header-section-number">4.1</span> General</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>probit_ai <span class="ot">&lt;-</span> <span class="fu">ologit.reg</span>(tier<span class="sc">~</span>like_rate<span class="sc">+</span>mark_rate</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>is_comic<span class="sc">+</span>is_Genshin</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>comments<span class="sc">+</span>top_cnt<span class="sc">+</span>date_diff_day</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span>like_rate2</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                  ,<span class="at">data=</span>ai)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(probit_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ordered Logit Regression 
Log-Likelihood: -11953.35 
No. Iterations: 4 
McFadden's R2: 0.08202672 
AIC: 23930.7 
                 Estimate  Std. error  t value              Pr(&gt;|t|)    
like_rate      -7.6473714   3.1331622  -2.4408             0.0146554 *  
mark_rate       9.0117247   0.8666315  10.3986 &lt; 0.00000000000000022 ***
is_comic1       1.2941907   0.3992273   3.2417             0.0011880 ** 
is_Genshin1    -0.1966665   0.0431047  -4.5625           0.000005054 ***
comments       -0.0568841   0.0055086 -10.3264 &lt; 0.00000000000000022 ***
top_cnt        -0.9275363   0.0339194 -27.3453 &lt; 0.00000000000000022 ***
date_diff_day  -0.4469178   0.0456232  -9.7958 &lt; 0.00000000000000022 ***
like_rate2    -34.9089146  10.4306529  -3.3468             0.0008176 ***
----- Threshold Parameters -----
                 Estimate Std. error  t value              Pr(&gt;|t|)    
Threshold (1-&gt;2) -2.39063    0.19356 -12.3509 &lt; 0.00000000000000022 ***
Threshold (2-&gt;3) -1.17121    0.19180  -6.1065        0.000000001019 ***
Threshold (3-&gt;4) -0.21450    0.19136  -1.1209                0.2623    
Threshold (4-&gt;5)  0.84643    0.19177   4.4138        0.000010158594 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We do not need to interpreter Threshold Parameters, the Estimate is the one we should focus on.</p>
<p>Whenever the variable like_rate increases, the probability for the rank tier-1 decreases,and tier-5 increases.</p>
</section>
<section id="marginal-effects" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="marginal-effects"><span class="header-section-number">4.2</span> Marginal Effects</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">margins.oglmx</span>(probit_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal Effects on Pr(Outcome==1)
                Marg. Eff  Std. error  t value              Pr(&gt;|t|)    
is_comic1     -0.11752676  0.02049728  -5.7338        0.000000009822 ***
is_Genshin1    0.02811899  0.00624449   4.5030        0.000006699912 ***
like_rate      1.08180567  0.44357108   2.4389             0.0147339 *  
mark_rate     -1.27480861  0.12432932 -10.2535 &lt; 0.00000000000000022 ***
comments       0.00804689  0.00079162  10.1651 &lt; 0.00000000000000022 ***
top_cnt        0.13121032  0.00512092  25.6224 &lt; 0.00000000000000022 ***
date_diff_day  0.06322149  0.00651992   9.6967 &lt; 0.00000000000000022 ***
like_rate2     4.93825390  1.47761720   3.3420             0.0008317 ***
------------------------------------ 
Marginal Effects on Pr(Outcome==2)
                Marg. Eff  Std. error t value              Pr(&gt;|t|)    
is_comic1     -0.13303405  0.03377827 -3.9385           0.000082009 ***
is_Genshin1    0.01956641  0.00427693  4.5749           0.000004765 ***
like_rate      0.76863679  0.31576591  2.4342             0.0149248 *  
mark_rate     -0.90576785  0.09126420 -9.9247 &lt; 0.00000000000000022 ***
comments       0.00571742  0.00057953  9.8657 &lt; 0.00000000000000022 ***
top_cnt        0.09322662  0.00453173 20.5720 &lt; 0.00000000000000022 ***
date_diff_day  0.04491968  0.00478805  9.3816 &lt; 0.00000000000000022 ***
like_rate2     3.50869269  1.05369282  3.3299             0.0008688 ***
------------------------------------ 
Marginal Effects on Pr(Outcome==3)
                Marg. Eff  Std. error t value     Pr(&gt;|t|)    
is_comic1     -0.06198087  0.03477036 -1.7826    0.0746550 .  
is_Genshin1   -0.00285341  0.00084642 -3.3711    0.0007486 ***
like_rate     -0.09799111  0.04434391 -2.2098    0.0271191 *  
mark_rate      0.11547352  0.02481797  4.6528 0.0000032743 ***
comments      -0.00072890  0.00015855 -4.5973 0.0000042791 ***
top_cnt       -0.01188517  0.00233185 -5.0969 0.0000003453 ***
date_diff_day -0.00572667  0.00123893 -4.6223 0.0000037958 ***
like_rate2    -0.44731228  0.15891020 -2.8149    0.0048796 ** 
------------------------------------ 
Marginal Effects on Pr(Outcome==4)
                Marg. Eff  Std. error  t value              Pr(&gt;|t|)    
is_comic1      0.06264069  0.00840777   7.4503    0.0000000000000931 ***
is_Genshin1   -0.01862433  0.00411450  -4.5265    0.0000059965192094 ***
like_rate     -0.72260324  0.29670858  -2.4354             0.0148755 *  
mark_rate      0.85152153  0.08515496   9.9997 &lt; 0.00000000000000022 ***
comments      -0.00537500  0.00054144  -9.9273 &lt; 0.00000000000000022 ***
top_cnt       -0.08764329  0.00391502 -22.3864 &lt; 0.00000000000000022 ***
date_diff_day -0.04222945  0.00446437  -9.4592 &lt; 0.00000000000000022 ***
like_rate2    -3.29855755  0.98983874  -3.3324             0.0008609 ***
------------------------------------ 
Marginal Effects on Pr(Outcome==5)
                Marg. Eff  Std. error  t value              Pr(&gt;|t|)    
is_comic1      0.24990099  0.09642931   2.5915             0.0095546 ** 
is_Genshin1   -0.02620766  0.00569466  -4.6021           0.000004182 ***
like_rate     -1.02984812  0.42212060  -2.4397             0.0146994 *  
mark_rate      1.21358141  0.11755404  10.3236 &lt; 0.00000000000000022 ***
comments      -0.00766041  0.00074424 -10.2929 &lt; 0.00000000000000022 ***
top_cnt       -0.12490848  0.00488126 -25.5894 &lt; 0.00000000000000022 ***
date_diff_day -0.06018506  0.00619144  -9.7207 &lt; 0.00000000000000022 ***
like_rate2    -4.70107677  1.40556103  -3.3446             0.0008239 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In the situation of Outcome==1 which is tier 1 in the Top, artwork about Genshin has higher probability than the artwork about other topics by 2.57407 percentage points. Additional thousands units of views or exposure would increase the probability of being tier 1 artwork in the Top by 0.456918 percentage points.</p>
</section>
</section>
<section id="summary" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Summary</h1>
</section>
<section id="references" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> References</h1>
<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-EconomicsChatGPT" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">A. Zarifhonarvar, <span>“Economics of ChatGPT: A labor market view on the occupational impact of artificial intelligence,”</span> <em>SSRN</em>, 2023, Available: <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4350925">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4350925</a></div>
</div>
<div id="ref-AIThemedCryptocurrencies" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">E. D. Lennart Ante, <span>“The ChatGPT effect on AI-themed cryptocurrencies,”</span> <em>SSRN</em>, 2023, Available: <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4350557">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4350557</a></div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'alternate';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>